---
apiVersion: v1
kind: Service
metadata:
  name: product-api
spec:
  selector:
    app: product-api
  ports:
    - name: http
      protocol: TCP
      port: 8500
      targetPort: 8500
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-api
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: product-api
spec:
  protocol: "http"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  config: |
    {
      "db_connection": "host=localhost port=8500 user=postgres password=password dbname=products sslmode=disable",
      "bind_address": ":8500",
      "metrics_address": ":8500"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  labels:
    app: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "postgres:8500"
        consul.hashicorp.com/enable-metrics-merging: "false"
    spec:
      serviceAccountName: product-api
      volumes:
      - name: config
        configMap:
          name: db-configmap
          items:
          - key: config
             path: conf.json
       containers:
         - name: product-api
           image: hashicorpdemoapp/product-api:v0.0.16
           ports:
             - containerPort: 8500
             - containerPort: 8500
          env:
            - name: "CONFIG_FILE"
              value: "/config/conf.json"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 30
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
